### ISSUE TITLE
定时任务自动添加

### ISSUE THREAD

**Issue by Mario-Lan** [KingRan/JDJB#43]
东东农场现在的js定时任务是 jd_fruit_task 文件默认还是jd_fruit

**Comment by KingRan** [comment]
jd_fruit_task日常任务



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月24日(星期一) 上午10:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [KingRan/JDJB] 定时任务自动添加 (Issue #43)





 
东东农场现在的js定时任务是 jd_fruit_task 文件默认还是jd_fruit
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Mario-Lan** [comment]
哦  我之前看到我的一直报这个错  ，我删掉script里的重新拉取也不行 。还有其他办法么
Error: Cannot find module './utils/share_code.js'
Require stack:
- /jd/scripts/backUp/jd_fruit.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/jd/scripts/backUp/jd_fruit.js:27:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/jd/scripts/backUp/jd_fruit.js' ]
}

**Comment by KingRan** [comment]
./utils/share_code.js&nbsp; 库里这个文件里面&nbsp;吧文件下载到你本地对应的就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月24日(星期一) 中午11:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KingRan/JDJB] 定时任务自动添加 (Issue #43)





 
哦  我之前看到我的一直报这个错  ，我删掉script里的重新拉取也不行 。还有其他办法么
 Error: Cannot find module './utils/share_code.js'
 Require stack:
  
/jd/scripts/backUp/jd_fruit.js
 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
 at Function.Module._load (internal/modules/cjs/loader.js:725:27)
 at Module.require (internal/modules/cjs/loader.js:952:19)
 at require (internal/modules/cjs/helpers.js:88:18)
 at Object. (/jd/scripts/backUp/jd_fruit.js:27:10)
 at Module._compile (internal/modules/cjs/loader.js:1063:30)
 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
 at Module.load (internal/modules/cjs/loader.js:928:32)
 at Function.Module._load (internal/modules/cjs/loader.js:769:14)
 at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
 code: 'MODULE_NOT_FOUND',
 requireStack: [ '/jd/scripts/backUp/jd_fruit.js' ]
 }
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Mario-Lan** [comment]
试过了 依旧不行 而且我看了以下 所有这个'/jd/scripts/backUp/jd_fruit.js'  backUp文件夹的都不行 ，提示的错误大同小异

**Comment by KingRan** [comment]
jd_fruit.js这个文件放在青龙面板脚本目录试试/jd/scripts/jd_fruit.js



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月24日(星期一) 下午3:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KingRan/JDJB] 定时任务自动添加 (Issue #43)





 
试过了 依旧不行 而且我看了以下 所有这个'/jd/scripts/backUp/jd_fruit.js'  backUp文件夹的都不行 ，提示的错误大同小异
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
