### ISSUE TITLE
添加任务报错，求教作者

### ISSUE THREAD

**Issue by sgkek** [KingRan/JDJB#48]
# 开始执行... 2022-02-02 09:35:51

开始克隆仓库 https://ghproxy.com/github.com/KingRan/JDJB.git 到 /ql/repo/KingRan_JDJB

更新/ql/repo/KingRan_JDJB成功...

检测到有新的定时任务：

KingRan_JDJB/jd_delete.py
KingRan_JDJB/jd_delete.py
KingRan_JDJB/jd_delete.py
KingRan_JDJB/jd_delete.py
KingRan_JDJB/jd_delete.py
KingRan_JDJB/jd_delete.py
KingRan_JDJB/jd_delete.py
KingRan_JDJB/jd_delete.py

开始尝试自动添加定时任务...

禁用重复任务 -> 添加失败(Constraint error, got value 0 expected range 1-31)
禁用重复任务 -> 添加失败(Constraint error, got value 0 expected range 1-31)
禁用重复任务 -> 添加失败(Constraint error, got value 0 expected range 1-31)
禁用重复任务 -> 添加失败(Constraint error, got value 0 expected range 1-31)
禁用重复任务 -> 添加失败(Constraint error, got value 0 expected range 1-31)
禁用重复任务 -> 添加失败(Constraint error, got value 0 expected range 1-31)
禁用重复任务 -> 添加失败(Constraint error, got value 0 expected range 1-31)
禁用重复任务 -> 添加失败(Constraint error, got value 0 expected range 1-31)
成员ID:@all企业微信应用消息发送通知消息成功🎉。

## 执行结束... 2022-02-02 09:47:12  耗时 681 秒

**Comment by KingRan** [comment]
【重要通知】
由于青龙默认使用了 https://ghproxy.com/ 这个Github代理加速，导致了请求量比较大的仓库被该代理加速作者封禁。


如遇到仓库更新失败，请看下面：
1.可以给宿主机挂代理并注释 config.sh 文件中的GithubProxyUrl参数解决
2.无法挂代理的可以修改青龙 config.sh 文件中的GithubProxyUrl参数为：
https://pd.zwc365.com/ 或&nbsp;
https://pd.zwc365.com/cfworker/ 临时解决。
3.或者使用cloudflare的workers搭建自己的加速地址，将文本中代码复制到workers保存并部署成功后 将CF分配的地址填入GithubProxyUrl中。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KingRan/JDJB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月2日(星期三) 上午10:13
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[KingRan/JDJB] 添加任务报错，求教作者 (Issue #48)





 
开始执行... 2022-02-02 09:35:51
 
开始克隆仓库 https://ghproxy.com/github.com/KingRan/JDJB.git 到 /ql/repo/KingRan_JDJB
 
更新/ql/repo/KingRan_JDJB成功...
 
检测到有新的定时任务：
 
KingRan_JDJB/jd_delete.py
 KingRan_JDJB/jd_delete.py
 KingRan_JDJB/jd_delete.py
 KingRan_JDJB/jd_delete.py
 KingRan_JDJB/jd_delete.py
 KingRan_JDJB/jd_delete.py
 KingRan_JDJB/jd_delete.py
 KingRan_JDJB/jd_delete.py
 
开始尝试自动添加定时任务...
 
禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31)
 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31)
 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31)
 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31)
 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31)
 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31)
 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31)
 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31)
 ***@***.***企业微信应用消息发送通知消息成功🎉。
 
执行结束... 2022-02-02 09:47:12  耗时 681 秒
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sgkek** [comment]
> 

你好作者，我在config.sh中没有找到GithubProxyUrl参数，您看一下是不是这个
## 代理地址，支持http/https/socks，例如 http://127.0.0.1:7890
ProxyUrl=""

**Comment by KingRan** [comment]
开始克隆仓库&nbsp;https://ghproxy.com/github.com/KingRan/JDJB.git&nbsp;到 /ql/repo/KingRan_JDJB
反正把&nbsp;https://ghproxy.com去掉才行！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KingRan/JDJB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月2日(星期三) 上午10:13
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[KingRan/JDJB] 添加任务报错，求教作者 (Issue #48)





 
开始执行... 2022-02-02 09:35:51
 
开始克隆仓库 https://ghproxy.com/github.com/KingRan/JDJB.git 到 /ql/repo/KingRan_JDJB
 
更新/ql/repo/KingRan_JDJB成功...
 
检测到有新的定时任务：
 
KingRan_JDJB/jd_delete.py
 KingRan_JDJB/jd_delete.py
 KingRan_JDJB/jd_delete.py
 KingRan_JDJB/jd_delete.py
 KingRan_JDJB/jd_delete.py
 KingRan_JDJB/jd_delete.py
 KingRan_JDJB/jd_delete.py
 KingRan_JDJB/jd_delete.py
 
开始尝试自动添加定时任务...
 
禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31)
 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31)
 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31)
 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31)
 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31)
 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31)
 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31)
 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31)
 ***@***.***企业微信应用消息发送通知消息成功🎉。
 
执行结束... 2022-02-02 09:47:12  耗时 681 秒
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sgkek** [comment]
> 开始克隆仓库&nbsp;[https://ghproxy.com/github.com/KingRan/JDJB.git&nbsp;到](https://ghproxy.com/github.com/KingRan/JDJB.git&nbsp;%E5%88%B0) /ql/repo/KingRan_JDJB 反正把&nbsp;[https://ghproxy.com去掉才行！](https://ghproxy.com%E5%8E%BB%E6%8E%89%E6%89%8D%E8%A1%8C%EF%BC%81)
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "KingRan/JDJB" ***@***.***&gt;; 发送时间:&nbsp;2022年2月2日(星期三) 上午10:13 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[KingRan/JDJB] 添加任务报错，求教作者 (Issue #48) 开始执行... 2022-02-02 09:35:51 开始克隆仓库 https://ghproxy.com/github.com/KingRan/JDJB.git 到 /ql/repo/KingRan_JDJB 更新/ql/repo/KingRan_JDJB成功... 检测到有新的定时任务： KingRan_JDJB/jd_delete.py KingRan_JDJB/jd_delete.py KingRan_JDJB/jd_delete.py KingRan_JDJB/jd_delete.py KingRan_JDJB/jd_delete.py KingRan_JDJB/jd_delete.py KingRan_JDJB/jd_delete.py KingRan_JDJB/jd_delete.py 开始尝试自动添加定时任务... 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31) 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31) 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31) 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31) 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31) 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31) 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31) 禁用重复任务 -&gt; 添加失败(Constraint error, got value 0 expected range 1-31) ***@***.***企业微信应用消息发送通知消息成功🎉。 执行结束... 2022-02-02 09:47:12 耗时 681 秒 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

谢谢作者这个问题已解决，谢谢。有些脚本出现下面问题，还想请教下怎么解决
第一个：🔔京东CK检测, 开始!

====================共3个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2022/2/2 10:30:01=====================

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './ql'
Require stack:
- /ql/scripts/KingRan_JDJB/jd_CheckCK.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/scripts/KingRan_JDJB/jd_CheckCK.js:16:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/KingRan_JDJB/jd_CheckCK.js' ]
}

**Comment by sgkek** [comment]
第二个
🔔京喜工厂, 开始!

====================共3个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2022/2/2 10:10:37=====================

开始获取京喜工厂配置文件

node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module './jdDreamFactoryShareCodes.js'
Require stack:
- /ql/scripts/KingRan_JDJB/jd_dreamFactory.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /ql/scripts/KingRan_JDJB/jd_dreamFactory.js:1419:37
    at new Promise (<anonymous>)
    at requireConfig (/ql/scripts/KingRan_JDJB/jd_dreamFactory.js:1394:10)
    at /ql/scripts/KingRan_JDJB/jd_dreamFactory.js:60:9
    at Object.<anonymous> (/ql/scripts/KingRan_JDJB/jd_dreamFactory.js:118:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/KingRan_JDJB/jd_dreamFactory.js' ]
}

## 执行结束... 2022-02-02 10:10:37 耗时 0 秒

**Comment by sgkek** [comment]
第三个，京喜工厂自动化，我两个账号都在生产着，以前用faker库的时候是正常的，作者帮看看这是什么原因
## 开始执行... 2022-02-02 11:24:15


====================共3个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2022/2/2 11:24:18=====================

2022-02-02 11:24:18.433 M京喜工厂自动化 /ql/scripts/KingRan_JDJB/jd_jx_factory_automation.js 开始运行...
2022-02-02 11:24:18.741 jd_55246182beab5 e Request failed with status code 401
2022-02-02 11:24:21.890 jd_QySvqyANRCaE jd_QySvqyANRCaE的梦工厂 等级 1
2022-02-02 11:24:21.891 jd_QySvqyANRCaE 获取工厂id 53994541
2022-02-02 11:24:21.891 jd_QySvqyANRCaE 获取设备id 53994542
2022-02-02 11:24:23.474 jd_QySvqyANRCaE 没找到你要生产的 你还没设置要生产的变量COMMODITY_NAME
2022-02-02 11:24:25.941 jd_5c20d77494b51 jd_178636yzn的梦工厂 等级 6
2022-02-02 11:24:25.942 jd_5c20d77494b51 还没有生产完成
2022-02-02 11:24:25.942 M京喜工厂自动化 运行结束,耗时 7508ms

成员ID:@all企业微信应用消息发送通知消息成功🎉。


## 执行结束... 2022-02-02 11:24:27 耗时 12 秒

**Comment by KingRan** [comment]
JDJB
完整库，集合可用脚本，账号互助，不添加助力池，适用于青龙面板。


频道：https://t.me/KingRan521&nbsp;&nbsp;


国内鸡：（TX云等）


修改青龙 config.sh 文件中的GithubProxyUrl参数为：
https://pd.zwc365.com/ 或&nbsp;
https://pd.zwc365.com/cfworker/


然后拉库命令填写下方代码：


ql repo https://github.com/KingRan/JDJB.git "jd_|jx_|jdCookie" "activity|backUp" "^jd[^_]|USER|utils|function|sign|sendNotify|ql|JDJR"


国外鸡直接填写下方代码


ql repo https://github.com/KingRan/JDJB.git "jd_|jx_|jdCookie" "activity|backUp" "^jd[^_]|USER|utils|function|sign|sendNotify|ql|JDJR"







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KingRan/JDJB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月2日(星期三) 上午10:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KingRan/JDJB] 添加任务报错，求教作者 (Issue #48)





   
你好作者，我在config.sh中没有找到GithubProxyUrl参数，您看一下是不是这个
 
代理地址，支持http/https/socks，例如 http://127.0.0.1:7890
 
ProxyUrl=""
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
